version: '3.3'

services:

  athena:
    container_name: athena
    build:
      context: .
      dockerfile: local.Dockerfile
    volumes:
      - '.:/Athena'
      - '/Athena/node_modules'
    restart: 'always'
    #    ports:
    #      - '8031:8890'
    #      - '3001:8891'
    environment:
      - NODE_ENV=production

